# Generated by Django 5.1.1 on 2024-12-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_cars_car_photo_cars_year_of_production'),
        ('carvideos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carvideo',
            name='tagged_cars',
            field=models.ManyToManyField(blank=True, to='cars.cars'),
        ),
    ]
