# Generated by Django 5.1.1 on 2024-12-10 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carvideos', '0005_alter_carvideoscomment_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carvideoslike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='carvideoslike',
            name='to_video',
        ),
        migrations.RemoveField(
            model_name='carvideoslike',
            name='user',
        ),
        migrations.DeleteModel(
            name='CarVideosComment',
        ),
        migrations.DeleteModel(
            name='CarVideosLike',
        ),
    ]
