# Generated by Django 5.1.1 on 2024-12-10 14:43

import ConnextoSocial.carvideos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carvideos', '0006_alter_carvideoslike_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carvideo',
            name='video',
            field=models.FileField(upload_to='car_videos/', validators=[ConnextoSocial.carvideos.validators.validate_video_length]),
        ),
    ]
