# Generated by Django 5.1.1 on 2024-12-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='car_photo',
        ),
        migrations.AddField(
            model_name='cars',
            name='year_of_production',
            field=models.DateField(blank=True, null=True),
        ),
    ]
