# Generated by Django 5.1.1 on 2024-11-30 14:35

import ConnextoSocial.carphotos.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_photo', models.ImageField(upload_to='', validators=[ConnextoSocial.carphotos.validators.FileSizeValidator(5)])),
                ('description', models.TextField(blank=True, max_length=433, null=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('location', models.CharField(blank=True, max_length=66, null=True)),
                ('date_of_publication', models.DateField(auto_now_add=True)),
                ('tagged_cars', models.ManyToManyField(blank=True, to='cars.cars')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
