# Generated by Django 5.1.1 on 2024-12-08 23:19

import ConnextoSocial.carphotos.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, max_length=433, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='/media/profile_pictures/default.jpg', upload_to='profile_pictures/', validators=[ConnextoSocial.carphotos.validators.FileSizeValidator(5)]),
            preserve_default=False,
        ),
    ]
