name: Build and deploy Python app to Azure Web App - connextosocial-second-demo-release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x '*.git*' 'venv/*'

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Debug Azure Subscriptions
        run: az account list --output table

      - name: Debug Role Assignments
        run: az role assignment list --assignee ${{ secrets.AZUREAPPSERVICE_CLIENTID_BE31D751408A4B6F8ADC5927F6C1A596 }} --output table

      - name: Debug Web App
        run: az webapp show --name 'connextosocial-second-demo-release' --resource-group '<resource-group-name>'

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BE31D751408A4B6F8ADC5927F6C1A596 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8C3B5797F6BF4BBDBC1C8029132D5CB6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6A39A60F215344919DEB39FD65B0C5F4 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'connextosocial-second-demo-release'
          slot-name: 'Production'
